@api = http://localhost:4000/api/products

GET {{api}}
###
GET {{api}}/1
###
GET {{api}}/count
###
POST {{api}}
Content-Type: application/json

{
   "productName": "Coaas Cola",
    "categoryId": 1,
    "unitPrice": 30,
    "unitsInStock": 100
}

###
PUT {{api}}/13
Content-Type: application/json

{
   "productName": "Pepsi Cola",
    "categoryId": 1,
    "unitPrice": 30,
    "unitsInStock": 100
}

###
DELETE {{api}}/15